### ISSUE TITLE
uk-Parameter zeigt Fehler 

### ISSUE THREAD

**Issue by Nicosiane** [AndreasFischer1985/weiterbildungssuche-api#9]
Ich beziehe mich auf api_example.R.

Bei Verwendung der URL: 
url="https://rest.arbeitsagentur.de/infosysbub/wbsuche/pc/v1/bildungsangebot?ssw=Teilquali&size=500&ort=Erlangen_11.005_49.595&uk=ort"
erscheint:
> data=jsonlite::fromJSON(rawToChar(httr::content(data_request)))
Error in rawToChar(httr::content(data_request)) : 
  argument 'x' must be a raw vector

Lässt man "&uk=ort" weg läuft der Job, aber bringt bundeweite Resultate.

Auch andere Versuche der regionalen Eingrenzung (z.B. re = BAY) scheinen nicht zu funktionieren, bringen aber keinen Fehler.

Übersehe ich was?

**Comment by AndreasFischer1985** [comment]
Vielen Dank für den Hinweis. Das Problem war der Parameter "ort", der eigentlich "orte" heißen müsste. Die Dokumentation habe ich eben entsprechend aktualisiert.

Mit Blick auf "ssw=Teilquali" möchte ich noch darauf hinweisen, dass sich die meisten Teilqualifizierungsangebote nicht in der Weiterbildungssuche, sondern in der Ausbildungssuche der Bundesagentur finden (für Erlangen z.B. [hier](https://web.arbeitsagentur.de/ausbildungssuche/berufsausbildung-suche?sty=0&seite=0&atyp=101&ort=38464&uk=25)) deren API ebenfalls auf bund.dev dokumentiert ist  ([hier](https://github.com/bundesAPI/ausbildungssuche-api)). Konkret findet man Teilqualifizierungen dort als Bildungsart (bart) 101 
([https://twitter.com/AFischer1985/status/1524872151853039617](https://twitter.com/AFischer1985/status/1524872151853039617))
